my_city/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from webpanels.views import LoginView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
		title="Reports API",
		default_version='v1',
		description="This is Swagger documentation for snippets",
		terms_of_service="https://www.google.com/policies/terms/",
		contact=openapi.Contact(email="contact@snippets.local"),
		license=openapi.License(name="BSD License"),
	),
	public=True,
	permission_classes=[permissions.AllowAny],
)

urlpatterns = [
	path('admin/', admin.site.urls),
	path('login/', LoginView.as_view(), name='login'),
	path('', include('webpanels.urls')),
	path('api/', include('reports.urls')),
	re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
	re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
	re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reports/urls.py
from django.urls import path, re_path
from rest_framework.routers import DefaultRouter
from .views import ReportsViewSet, CommentCreateView

app_name = 'api'
router = DefaultRouter()
router.register(r'reports', ReportsViewSet, basename='reports')


# urlpatterns = [
#     path('reports/', ReportsListView.as_view(), name='report_list'),
# ]
urlpatterns = router.urls
urlpatterns += [
    path('coments/<int:report_id>', CommentCreateView.as_view(), name='comment_create'),
]

webpanels/urls.py
from django.urls import path, re_path
from .views import AllReportsView, SingleReportView, LoginView, update_report

app_name = 'webpanels'

urlpatterns = [
    path('reports/<int:pk>/', update_report, name='report_details'),
    # path('reports/<int:pk>/edit', UpdateReportView.as_view(), name='report_update'),
    path('', AllReportsView.as_view(), name='reports'),
]

reports/models.py
# from django.contrib.gis.db.models import PointField
from django.db import models
from django.contrib.auth.models import User


class Report(models.Model):
	title = models.CharField(max_length = 150)
	text = models.CharField(max_length = 600)
	# location_latlng = PointField() # for postgres
	location = models.JSONField(default=str)
	importance = models.BooleanField(default=False)
	rank = models.IntegerField(default=0)
	done = models.BooleanField(default=True)
	created_at = models.DateTimeField(auto_now_add=True)
	edited_at = models.DateTimeField(auto_now=True)
	

	def __str__(self):
		return f"{self.pk} - {self.title}"


class ReportImage(models.Model):
	img = models.ImageField(upload_to='report_images')
	report = models.ForeignKey(Report, on_delete=models.CASCADE)
	

class Comment(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	text = models.CharField(max_length = 350)
	report = models.ForeignKey(Report, on_delete=models.CASCADE, related_name='comments')
	
	
	

webpanels/models.py
from django.db import models

# Create your models here.

webpanels/forms.py
from django import forms
from reports.models import Report, Comment


CHOICES = [(True, 'Важное'), (False, 'Обычное')]


class ReportForm(forms.ModelForm):
	title = forms.CharField(max_length = 150)
	text = forms.CharField(max_length = 600)
	location = forms.CharField(max_length = 150)
	importance = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)


	class Meta:
		model = Report
		fields = ('title', 'text', 'location', 'importance')


class CommentForm(forms.ModelForm):
	
	class Meta:
		model = Comment
		fields = ('text',)
	# comment = forms.CharField(max_length = 350)

reports/views.py
from .models import Report, ReportImage, Comment
from rest_framework import generics
from .serializers import ReportSerializer, CommentSerializer, VoteSerializer
from rest_framework.response import Response
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from django.contrib.auth.models import User
from rest_framework.parsers import MultiPartParser, JSONParser
from django.db.models import F



class CommentCreateView(generics.CreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def perform_create(self, serializer):
        serializer.save(author=User.objects.first(), report=Report.objects.get(pk=self.kwargs.get('report_id')))


class ReportsViewSet(viewsets.ModelViewSet):
    serializer_class = ReportSerializer
    queryset = Report.objects.all()
    parser_classes = (MultiPartParser, JSONParser)


    @action(detail=True, methods=['post'], serializer_class=VoteSerializer)
    def set_vote(self, request, pk=None):
        report = self.get_object()
        user = User.objects.get(pk=1)
        serializer = VoteSerializer(data=request.data)
        if serializer.is_valid():
            report.rank = F('rank') + serializer.validated_data['vote']
            report.save()
            return Response({'status': 'vote is set'})
        else:
            return Response(serializer.errors,
                            status=status.HTTP_400_BAD_REQUEST)

webpanels/views.py
from django.views.generic import ListView, TemplateView, DetailView, FormView
from reports.models import Report, ReportImage
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from .forms import ReportForm, CommentForm


class DashBoardView(TemplateView):
    template_name = "dashboard_home.html"


class LoginView(TemplateView):
    template_name = "login.html"


class AllReportsView(ListView):
    model = Report
    template_name = "dashboard_home.html"

class SingleReportView(DetailView):
    model = Report
    template_name = "webpanels/report_detail.html"


def update_report(request, pk):
    report = Report.objects.get(pk=pk)
    # report = get_object_or_404(Report, pk=pk)
    form_report = ReportForm(instance=report)
    form_comment = CommentForm(request.POST or None)
    if request.method == 'POST':
        form_report = ReportForm(request.POST, instance=report)
        if form_report.is_valid():
            updated_report = form_report.save()
        if form_comment.is_valid():
            new_comment = form_comment.save()
        if update_report and new_comment:
            return HttpResponseRedirect(reverse("webpanels:reports"))
    
    context = {
        'form_report': form_report,
        'form_comment': form_comment
    }
    return render(request, 'webpanels/report_detail.html', context)


# class UpdateReportView(FormView):
#     model = Report
#     template_name = "webpanels/report_detail.html"
#     form_class = ReportForm

#     def get_form_kwargs(self):
#         form_kwargs = super(UpdateReportView, self).get_form_kwargs()
#         if 'pk' in self.kwargs:
#             form_kwargs['initial'] = get_object_or_404(Report, pk=int(self.kwargs['pk']))
#         return form_kwargs

#     def post(self, request, *args, **kwargs):
#         form = self.get_form()
#         print(form)
#         return HttpResponseRedirect(reverse("webpanels:reports"))
        

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %} | Панель администрирования "Мой город"</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
    <!--===============================================================================================-->	
        <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
    <!--===============================================================================================-->	
        <link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/login.html
{% block login %}

<div class="limiter">
    <div class="container-login100" style="background-image: url('images/bg-01.jpg');">
        <div class="wrap-login100 p-t-30 p-b-50">
            <span class="login100-form-title p-b-41">
                Account Login
            </span>
            <form class="login100-form validate-form p-b-33 p-t-5">

                <div class="wrap-input100 validate-input" data-validate = "Enter username">
                    <input class="input100" type="text" name="username" placeholder="User name">
                    <span class="focus-input100" data-placeholder="&#xe82a;"></span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="Enter password">
                    <input class="input100" type="password" name="pass" placeholder="Password">
                    <span class="focus-input100" data-placeholder="&#xe80f;"></span>
                </div>

                <div class="container-login100-form-btn m-t-32">
                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>

            </form>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>
{% endblock login %}

templates/webpanels/report_detail.html
{% extends '_base.html' %}

{% block title %}
    жалоба №{{object.pk}}
{% endblock title %}

{% block content %}
    <h2>Жалоба №{{object.pk}}|{{object.title}}</h2>
    <p>{{object.text}}</p>
    {% for picture in object.reportimage_set.all %}
        <img src="{{picture.img.url}}" alt="">
    {% empty %}
        <tr>No pictures</tr>
    {% endfor %}
    <a href="{% url 'webpanels:reports' %}">Назад</a>
    <form action="." method="post">
        {% csrf_token %}
        {{form_report}}
        Напишите комментарий:
        {{form_comment}}
        <button type="submit">Отправить</button>
    </form>
{% endblock content %}

templates/webpanels/report_list.html
{% extends '_base.html' %}

{% block title %}
    Список жалоб
{% endblock title %}

{% block content %}
<h2>List of reports here</h2>
<table>
    <th>
        <td>ID</td>
        <td>Title</td>
        <td>Author</td>
        <td>Urgent</td>
    </th>
    {% for report in object_list %}
    <tr>
        <td>{{report.pk}}</td>
        <td><a href="{% url 'webpanels:report_details' pk=report.pk %}">Report {{report.pk}}</a></td>
        <td>User23432</td>
        <td>Not urgent</td>
    </tr>
    {% empty %}
        <tr>No reports found</tr>
    {% endfor %}

-->Pagination
{% endblock content %}